WANDCRAFT_REDUCE_FIRE_RATE_WAIT = 10
WANDCRAFT_REDUCE_RELOAD_TIME = 10
WANDCRAFT_INCREASE_MANA_MAX = 150
WANDCRAFT_INCREASE_MANA_CHARGE_SPEED = 35
WANDCRAFT_INCREASE_DECK_CAPACITY = 1
WANDCRAFT_INCREASE_ACTIONS_PER_ROUND = 1
WANDCRAFT_REDUCE_SPREAD_DEGREES = 1